Repository ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-eixo-3-conecta, pull requests merged in 2024-12, with the labels that each got.

#105 design: adiciona modificações na landing page
  src/css/index.css
  src/index.html
  src/pages/landing-page/landing-page.css
Labels: design

#106 docs: adiciona relatório de testes
  docs/assets/documentos-de-teste/Avaliação_Heurística- Conecta.xlsx
  docs/assets/documentos-de-teste/relatórios-de-teste-usuário/Relatório_de_Testes_com_Usuário_Alice_ONG.docx
  docs/assets/documentos-de-teste/relatórios-de-teste-usuário/Relatório_de_Testes_com_Usuário_Davih_Voluntário.docx
  docs/assets/documentos-de-teste/relatórios-de-teste-usuário/Relatório_de_Testes_com_Usuário_Gabriel_Voluntário.docx
  docs/assets/documentos-de-teste/relatórios-de-teste-usuário/Relatório_de_Testes_com_Usuário_Leo_ONG.docx
  docs/assets/documentos-de-teste/relatórios-de-teste-usuário/Relatório_de_Testes_com_Usuário_Omar_ONG.docx
  docs/testes.md
Labels: documentation

#108 design: alinha textos em páginas informativas
  src/pages/como-comecar/como-comecar.css
  src/pages/perguntas-frequentes/perguntas-frequentes.css
  src/pages/por-que-ser-voluntario/por-que-ser-voluntario.css
  src/pages/sobre-o-voluntariado/sobre-o-voluntariado.css
Labels: design

#109 design: altera header e footer
  src/components/footer/footer.js
  src/components/header/header.js
  src/css/index.css
  src/pages/historias-sucesso/historias-sucesso.html
  src/pages/login/login.css
  src/pages/por-que-ser-voluntario/por-que-ser-voluntario.html
  src/pages/sobre-o-voluntariado/sobre-o-voluntariado.html
Labels: design

#112 fix: corrige texto de como ajudar não sendo apresentado
  src/js/models/candidacy.js
  src/pages/administrar-demanda/administrar-demanda.js
  src/pages/candidatar-a-demanda/candidatar-a-demanda.js
Labels: bug
